### ISSUE TITLE
error when uploading 

### ISSUE THREAD

**Issue by anya-ji** [longouyang/nosub#9]
When I tried to upload, I got this error. Any idea? Thanks!
```
(node:37608) UnhandledPromiseRejectionWarning: Error: connect EHOSTDOWN 169.254.169.254:80 - Local (10.48.103.228:63554)
    at internalConnect (net.js:921:16)
    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)
    at net.js:1009:9
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37608) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37608) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by longouyang** [comment]
I think you might not have set up your AWS credentials properly - what file did you store your credentials in and in what format?

**Comment by anya-ji** [comment]
In my root directory, I have .aws/credentials 
```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...
```
that I copied directly from AWS. Is there any additional setup?

**Comment by anya-ji** [comment]
I got a new error saying that 
```
RequestError: To use the MTurk API, you will need an Amazon Web Services (AWS) Account. Your AWS account must be linked to your Amazon Mechanical Turk Account. Visit https://requestersandbox.mturk.com/developer to get started.
```
although I set it up as above and when I go to that URL it says I'm linked to an mturk account. However I'm still getting this error.

**Comment by longouyang** [comment]
what kind of billing setup do you have? if you are using "AWS Billing" rather than pre-paid HITs, then you need to preface commands with `AWS_BILLING=1`, see this thread: https://github.com/longouyang/nosub/issues/8

**Comment by anya-ji** [comment]
I see. It seems to have something to do with our linked accounts. Will reopen if it's something else. Thanks for the help!
